/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   Do not edit this file directly. Any changes will be lost.           ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import type Opa5 from "sap/ui/test/Opa5";
import type { actions as ListReportActions, assertions as ListReportAssertions } from "sap/fe/test/ListReport";
import type { actions as ObjectPageActions, assertions as ObjectPageAssertions } from "sap/fe/test/ObjectPage";
import type { actions as TemplatePageActions, assertions as TemplatePageAssertions } from "sap/fe/test/TemplatePage";
import type Shell from "sap/fe/test/Shell";
import type BaseArrangements from "sap/fe/test/BaseArrangements";
import type { actions as ExpiryHeaderListGeneratedCustomActions, assertions as ExpiryHeaderListGeneratedCustomAssertions } from "../pages/ExpiryHeaderList.gen";
import type { actions as ExpiryHeaderObjectPageGeneratedCustomActions, assertions as ExpiryHeaderObjectPageGeneratedCustomAssertions } from "../pages/ExpiryHeaderObjectPage.gen";
import type { actions as ExpiryItemObjectPageGeneratedCustomActions, assertions as ExpiryItemObjectPageGeneratedCustomAssertions } from "../pages/ExpiryItemObjectPage.gen";

export type Given = Opa5 & BaseArrangements & {
    iTearDownMyApp: () => Given;
    iStartMyApp: (sAppHash?: string, mInUrlParameters?: object) => Given;
    and: Given;
};

export type When = Opa5 & BaseArrangements & {
    onTheExpiryHeaderListGenerated: Opa5 & ListReportActions & TemplatePageActions & typeof ExpiryHeaderListGeneratedCustomActions;
    onTheExpiryHeaderObjectPageGenerated: Opa5 & ObjectPageActions & TemplatePageActions & typeof ExpiryHeaderObjectPageGeneratedCustomActions;
    onTheExpiryItemObjectPageGenerated: Opa5 & ObjectPageActions & TemplatePageActions & typeof ExpiryItemObjectPageGeneratedCustomActions;
    onTheShell: Shell;
};

export type Then = Opa5 & BaseArrangements & {
    onTheExpiryHeaderListGenerated: Opa5 & ListReportAssertions & TemplatePageAssertions & typeof ExpiryHeaderListGeneratedCustomAssertions;
    onTheExpiryHeaderObjectPageGenerated: Opa5 & ObjectPageAssertions & TemplatePageAssertions & typeof ExpiryHeaderObjectPageGeneratedCustomAssertions;
    onTheExpiryItemObjectPageGenerated: Opa5 & ObjectPageAssertions & TemplatePageAssertions & typeof ExpiryItemObjectPageGeneratedCustomAssertions;
    onTheShell: Shell;
};
