/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes";
import type { FormIdentifier } from "sap/fe/test/api/FormAPI";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("ExpiryHeaderObjectPageObjectPage journey");

    opaTest("Navigate to ExpiryHeaderObjectPageObjectPage", function (Given: Given, When: When, Then: Then) {
        Given.iStartMyApp();
        When.onTheExpiryHeaderListGenerated.onFilterBar().iExecuteSearch();
        Then.onTheExpiryHeaderListGenerated.onTable("").iCheckRows();
        When.onTheExpiryHeaderListGenerated.onTable("").iPressRow(0);

        Then.onTheExpiryHeaderObjectPageGenerated.iSeeThisPage();
    });



    opaTest("Check body sections of the Object Page", function (_Given: Given, When: When, Then: Then) {
        Then.onTheExpiryHeaderObjectPageGenerated.iCheckNumberOfSections(2);
        When.onTheExpiryHeaderObjectPageGenerated.iPressSectionIconTabFilterButton("HeaderInfo");
        Then.onTheExpiryHeaderObjectPageGenerated.iCheckSection({ section: "HeaderInfo" }, {});
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "Plant" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "DisplayMaterialNumber" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "MaterialDescription" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "MaterialBaseUnit" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "MaterialType" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "DisplayBatchNumber" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "StorageLocationCode" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "ManufacturerName" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "LastGRDate" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "ManufactureDate" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "ExpiryDate" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "RetestDate" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "RemainingDaysToExpire" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "UnrestrictedQty" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "BlockedQty" });
        Then.onTheExpiryHeaderObjectPageGenerated.onForm({ section: "HeaderInfo" } as unknown as FormIdentifier).iCheckField({ property: "TotalValue" });
        When.onTheExpiryHeaderObjectPageGenerated.iPressSectionIconTabFilterButton("WhereUsed");
        Then.onTheExpiryHeaderObjectPageGenerated.iCheckSection({ section: "WhereUsed" }, {});
        Then.onTheExpiryHeaderObjectPageGenerated.onTable({ property: "_WhereUsed" }).iCheckColumns(undefined, {"ParentFinishedGood":{"header":"Parent Finished Good"},"ParentFinishedGoodDesc":{"header":"Parent FG Description"},"DisplayMaterialNumber":{"header":"Component Material"},"DisplayBatchNumber":{"header":"Batch No."}});
   });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
