/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("ExpiryHeaderListListReport journey");

    const defaultTableId = "";

    opaTest("Start application", function (Given: Given, _When: When, Then: Then) {
        Given.iStartMyApp();

        Then.onTheExpiryHeaderListGenerated.iSeeThisPage();
    });

    opaTest("Check filter bar", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheExpiryHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "Plant" });
        Then.onTheExpiryHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "DisplayMaterialNumber" });
        Then.onTheExpiryHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "DisplayBatchNumber" });
        Then.onTheExpiryHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "StorageLocationCode" });
    });

    // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
    // opaTest("Perform a global search and check the result", function (Given: Given, When: When, Then: Then) {
    //     When.onTheExpiryHeaderListGenerated.onFilterBar().iChangeSearchField("Search Term");
    //     When.onTheExpiryHeaderListGenerated.onFilterBar().iExecuteSearch();
    //     Then.onTheExpiryHeaderListGenerated.onTable(defaultTableId).iCheckRows();
    // });

    opaTest("Check table columns and actions", function (_Given: Given, _When: When, Then: Then) {
        // When.onTheExpiryHeaderListGenerated.onTable(defaultTableId).iPressAction("Download");
        Then.onTheExpiryHeaderListGenerated.onTable(defaultTableId).iCheckAction("Download", { enabled: true });
        Then.onTheExpiryHeaderListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Plant":{"header":"Plant"},"MaterialNumber":{"header":"Material"},"DisplayMaterialNumber":{"header":"Material code"},"MaterialDescription":{"header":"Material Description"},"MaterialBaseUnit":{"header":"UOM"},"MaterialType":{"header":"Material type"},"DisplayBatchNumber":{"header":"Batch No."},"StorageLocationCode":{"header":"St. Location"},"ManufacturerName":{"header":"Manufacturer Part No."},"LastGRDate":{"header":"GR Date (Receiving Date)"},"ManufactureDate":{"header":"Manufacturing Date"},"ExpiryDate":{"header":"Expiry Date"},"RetestDate":{"header":"Retest Date"},"RemainingDaysToExpire":{"header":"Remaining Shelf-life (In days)"},"UnrestrictedQty":{"header":"Unrestricted QTY"},"BlockedQty":{"header":"Blocked QTY"},"TotalValue":{"header":"Value of QTY"}});
    });

    opaTest("Navigate to ObjectPage", function (_Given: Given, When: When, Then: Then) {
        // Note: this test will fail if the ListReport page doesn't show any data
        When.onTheExpiryHeaderListGenerated.onFilterBar().iExecuteSearch();
        Then.onTheExpiryHeaderListGenerated.onTable(defaultTableId).iCheckRows();
        When.onTheExpiryHeaderListGenerated.onTable(defaultTableId).iPressRow(0);
        Then.onTheExpiryHeaderObjectPageGenerated.iSeeThisPage();
    });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
